name: CI

on:
  push:
    branches: [main, master, develop]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.json'
  pull_request:
    branches: [main, master, develop]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.json'

# Cancel in-progress runs for the same PR or branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: test
  PYTHON_VERSION: '3.11'

defaults:
  run:
    working-directory: ./

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
        python-version: ['3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js setup with caching
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Python setup with caching
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      # Install dependencies
      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Linting
      - name: Run ESLint
        run: npm run lint

      - name: Run Python linters
        run: |
          ruff check .
          black --check .
          mypy .

      # Testing
      - name: Run Node.js tests
        run: npm test
        env:
          NODE_ENV: test

      - name: Run Python tests with coverage
        run: |
          pytest --cov=divina --cov-report=xml
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false

  build:
    name: Build
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist/
            package.json
            package-lock.json