name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint (if available)
        run: npm run lint || true

      - name: Run tests
        run: npm test || true

      - name: Run E2E tests
        run: npm run test:e2e || true

      - name: Upload coverage (if available)
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/ 