name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, master, develop]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install pre-commit
        run: pip install pre-commit
        
      - name: Set up pre-commit hooks
        run: pre-commit install --install-hooks
        
      - name: Run pre-commit on all files
        run: pre-commit run --all-files --show-diff-on-failure
