name: Umbrella CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "no requirements.txt"; fi
          pip install pytest || true
          pip install ruff || true
      - name: Lint (ruff if present)
        run: ruff check . || echo "no ruff"
      - name: Test (if present)
        run: pytest || echo "no tests"
